### ISSUE TITLE
Fresh install stops with this message

### ISSUE THREAD

**Issue by vagifverdi** [JPMoresmau/eclipsefp#186]
Tried to install latest eclipsefp 2.6.0

Ubuntu 14.04, ghc 7.6.3, cabal-install 1.20.

I did it with a fresh .cabal and .ghc folders. Nothing elase was installed.

After restarting eclipse it started doenloading and building haskell libs, and stopped with this error:

Cabal==1.16.0/installed-c6e..., SourceGraph => Cabal<1.7)
rejecting: SourceGraph-0.2, 0.1 (conflict: buildwrapper =>
Cabal==1.16.0/installed-c6e..., SourceGraph => Cabal<1.5)
Backjump limit reached (change with --max-backjumps).

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.

I'm not sure what does that mean. Is eclipsefp broken for me, or is it just some minor feature that will be not available? Can i still use it or do i have ti solve this problem?

Also on haskell cafe i've been told that eclipsefp expects cabal 1.16 with ghc 7.6.3 and i have cabal 1.20

Is this correct?

**Comment by JPMoresmau** [comment]
SourceGraph is not installed by default any more
