### ISSUE TITLE
Easy way to find sources and executable with one click

### ISSUE THREAD

**Issue by varosi** [JPMoresmau/eclipsefp#209]
On Visual Studio there is a very helpful feature - right-click over the current opened file title then in the context menu: Open Containing Folder. Then it opens default file manager (in Windows it is Windows Explorer with the folder that contains that file). There is no need to browse any more in complex folder structure to find a single source file.

If it is possible to add this to source files as well to cabal configuration right click for directly opening folder that is containing the last built executable file?

**Comment by JPMoresmau** [comment]
This is a Eclipse level functionality, not Haskell specific. Contact the Eclipse maintainers.
