### ISSUE TITLE
EclipseFP attempts to cabal install in each workspace without prompting the user

### ISSUE THREAD

**Issue by rpglover64** [JPMoresmau/eclipsefp#238]
I understand that it's useful to have all the programs installed without prompting the user, but I have Eclipse workspaces that I don't use for Haskell development, and I found it slightly disturbing how difficult it was to stop the install when I switched to one.

I think a good heuristic would be to remember if the install has ever happened (on a plugin level) and query the user if it has but the current workspace does not seem to have the appropriate tooling installed.

**Comment by JPMoresmau** [comment]
This has been done in 2.6.3. The tool sandbox is common to all workspaces.
