### ISSUE TITLE
Warning and solution for library version conflict when installing

### ISSUE THREAD

**Issue by pvillela** [JPMoresmau/eclipsefp#241]
I installed EclipseFP with Haskell Platform 2014.2.0.0.  When I started EclipseFP on a workspace, it automatically created a cabal sandbox and started installing the required libraries.  At the end of the install, there was a message in the console about a conflict between aeson and scion-browser.  I was able to resolve the issue by cd'ing to the sandbox folder and running

    cabal install aeson scion-browser

This caused the version of aeson to be downgraded and scion-browser was successfully installed.

This conflict can be very frustrating to new users of the tool, so a warning and workaround tip in the documentation should be welcome.

**Comment by JPMoresmau** [comment]
Bounds have been fixed now.
