### ISSUE TITLE
Using HLint.hs file

### ISSUE THREAD

**Issue by razvan-panda** [JPMoresmau/eclipsefp#252]
StackOverlfow question: http://stackoverflow.com/q/27706547/750216

Is it possible to use HLint.hs file to customize HLint messages in EclipseFP?

I tried adding a HLint.hs file in the project root containing:

    import "hint" HLint.HLint

    ignore "Use camelCase"

but it has no effect.

**Comment by razvan-panda** [comment]
I did made sure to change the files after placing the `HLint.hs` file in root but it is still not working.

Could you please have a look at what I tried, maybe you can spot the problem: github.com/razvan-panda/EclipseFP-HTF-test-example

The camel-case warnings should be ignored from the LibTest.hs.

Thank you

**Comment by JPMoresmau** [comment]
I don't get any warning even if I remove the line `ignore "Use camelCase"` in your `HLint.hs` file. If I use `import "hint" HLint.HLint` then I see the warning. I add `ignore "Use camelCase"` and the warnings disappear.

**Comment by razvan-panda** [comment]
I have tested the steps you described and it is still not working. No matter what is set in `HLint.hs` the warnings are still being shown (even after EclipseFP and waiting for the plugin to do its stuff). There must be something that we are doing different.

Reopening the issue since it is not fixed.

**Comment by JPMoresmau** [comment]
Well no, since it's not reproducible, and it works fine WITH YOUR OWN DATA. The code responsible for this (using the project location as the working directory for Hlint) has been in place for more than a year.

**Comment by razvan-panda** [comment]
Sorry for the late reply. For HLint to pick up the changes in the HLint.hs file it is required to run `Cabal install dependencies`. Is this intended usage?

Just waiting for EclipseFP to do its stuff has no effect on showing/hiding the HLint warnings.
