### ISSUE TITLE
Haskell Console window colors cannot be changed

### ISSUE THREAD

**Issue by varosi** [JPMoresmau/eclipsefp#256]
To save my eyes I'm trying to use dark color themes on editors I'm working with.
Eclipse Luna has built in support for Dark color theme.

But the dark blue color of Haskell Console window cannot be changed. And it looks almost unreadable on dark background. Unfortunately I cannot find where it could be changed. 
It will be great if there is an option for that. Even greater will be if EclipseFP has support for Eclipse Luna standard color themes and change its colors accordingly.

**Comment by razvan-panda** [comment]
@varosi Which dark color theme did you use that worked well with EclipseFP? I tried one in the past but the text colors were quite unreadable.

**Comment by varosi** [comment]
1. Eclipse Luna
2. Eclipse Color Theme plug-in
3. Window | Preferences | General | Appearance | Theme -> Dark
4. Window | Preferences | General | Appearance | Color Theme -> Sublime Text 2

This works well for me and if you would like to customize even more you could do it from:
Window | Preferences | Haskell | Editor | Syntax

**Comment by razvan-panda** [comment]
@varosi Thank you, this works pretty well. :)
I had used the same plug-in but did not notice the Color Theme page under Appearance group.

**Comment by varosi** [comment]
You are welcome!
