### ISSUE TITLE
Stable distro of EclipseFP with all its tools

### ISSUE THREAD

**Issue by varosi** [JPMoresmau/eclipsefp#258]
Do you think of a stable working distro that is easily installed (by as less steps as possible) that includes (depends) on certain guaranteed versions of its tools (buildwrapper, scion-browser, etc)?
Like Platform Haskell for Haskell. 
This will ease installation and entry to use EclipseFP as a Haskell IDE. Like in Windows when you install Visual Studio it either installs successfully, either not installs at all and if it installs you know that it is working and has everything needed for a start of development process.

Currently there a lot of issues that arises until we have a working environment for Haskell using EclipseFP.

Some of features that could help this are:
1. Install all pre-requisites at EclipseFP installation, not later. 
2. Install in a sandbox only fixed versions of buildwrapper, scion-browser, hoogle, etc. that are guaranteed to work with current EclipseFP and Platform Haskell versions. Building should be solid. I mean - build each tool as a fresh build with force rebuilding of dependencies into this sandbox.
3. This sandbox to be per EclipseFP installation and not per Eclipse workspace
4. Installation to be as transactional as possible. This means that if all components that are needed are not installed - to roll back and not finish the installation. So we have to check log, fix and retry. This way we'll not have half working EclipseFP with unknown state.

Those features are a big deal in my oppinion and in my experiance with preparing working environments for developers.

**Comment by JPMoresmau** [comment]
EclipseFP is a one man project aimed at developers that should be able to install tools themselves if need be. If you want all of this, develop it and send a pull request.

**Comment by varosi** [comment]
Thanks for the clarification!

I just think of ways to help EclipseFP be more successful, popular and easier to use.
I hope that you don't ignore user feedback.
