### ISSUE TITLE
version 2.6.2.201411231617  - mac - sandboxing does not appear to work with cabal 1.22

### ISSUE THREAD

**Issue by jason-johnson** [JPMoresmau/eclipsefp#260]
I'm on an imac, using macports.  My steps were:  

1. install the latest GHC (7.8.3) from macports
2. Install cabal from macports.
3. With this cabal I simply do a `cabal install cabal-install` to get the latest version
4. uninstall the ports cabal.
5. cabal install alex and happy.  
6. Create a sandbox for the tools eclipse uses [1] and install them.  
7. install the latest Luna Eclipse mac package.  
8. install eclipsefb as described on the website.
9. open a fresh workspace and enter the location to all the required tools (note: I do not build SourceGraph because it requires its own sandbox and I don't actually use it anyway).  
10. add my Haskell project to the workspace (the project was working perfectly in a previous version of eclipsefp/Luna).

I have tried a lot of things here but it seems the combination of incompatible tools and dependencies means the only way to get the project working now is to use sandboxing but this also appears not to work.  I am using cabal 1.22 so I don't see why I need cabal-dev but eclipsefb does not seem to recognise sandboxes it didn't create itself.  I went into the project sandbox which I have configured with "Use Cabal Sandboxes" and "Use same sandbox for all projects in workspace" but when I force the project to build it still fails claiming the dependencies are not met.  Indeed, if I do a "cabal install dependancies" it installs to my main .cabal directory and breaks everything again (project won't build because it can't find cabal.1.22....).   Am I meant to be using the legacy cabal-dev here?  I'm at a loss how this works at all with the newest version of eclipsefp.

[1]  When I first tried this, I configured eclipsefb with my cabal and restarted.  This caused eclipsefp to create its own sandbox under .metadata/.plugins.  It ultimately seemed to fail because it was trying to build SourceGraph which crashed, presumably blocking what ever remaining steps would have come after it.  I made my own sandbox under the .cabal directory so that all my workspaces can share the same set of tools, but after understanding how this works a bit better I tried to go back to the previous configuration... only now eclipsefb doesn't build the sandbox anymore and I'm not sure where it tries to install everything because it still fails with SourceGraph but now it no longer fills in the path for e.g. scion-browser either.

**Comment by JPMoresmau** [comment]
I don't have a Mac so maybe there are mac specifc issues there, but:
- You should not use cabal-dev, EclipseFP supports cabal sandboxes, and
hopefully the whole system has not changed in 1.22
- EclipseFP uses 2 different sandboxes by default. One for the tools
(buildwrapper, scion-browser, hlint, etc) and one for the projects if you
checked "use same sandbox for all projects". By default the tool sandbox is
in the eclipsefp.haskell.ui plugin and the project sandbox in the
buildwrapper plugin.
- So whatever happens in the "tool" sandbox (failing because of
SourceGraph, etc) does not impact your "projects" sandbox
- As you did, you can always use tools built in another sandbox, somewhere
else, etc. Once the path are set in the preferences, EclipseFP should use
these and not try to rebuild the tools. For example, I usually work with a
development version of buildwrapper so I use the exe built in my
buildwrapper project and not the one from Hackage.
- A project referencing a sandbox should have a cabal.sandbox.config file.
Check that this file exists for your project and points to the proper
sandbox. If you have this file, then any standard cabal operations in that
folder will use the sandbox. EclipseFP should create this file as it runs
cabal sandbox init in the project directory if needed.
- Ensure the path to Cabal is correct in the EclipseFP preferences and the
version indicated is 1.22.

Hope this helps.

JP

On Thu, Jan 8, 2015 at 10:33 PM, jason-johnson <notifications@github.com>
wrote:

> I'm on an imac, using macports. My steps were: install the latest GHC
> (7.8.3) from macports, then install cabal from macports. With this cabal I
> simply do a cabal install cabal-install to get the latest version, then
> uninstall the ports version.
>
> Next I cabal install alex and happy. Then I created a sandbox for the
> tools eclipse uses [1]. Then I install the latest Luna Eclipse mac package.
> And then I install eclipsefb as described on the website. I open a fresh
> workspace and enter the location to all the required tools (note: I do not
> build SourceGraph because it requires its own sandbox and I don't actually
> use it anyway). After all this is done, I add my Haskell project to the
> workspace (the project was working perfectly in a previous version of
> eclipsefp/Luna).
>
> I have tried a lot of things here but it seems the combination of
> incompatible tools and dependencies means the only way to get the project
> working now is to use sandboxing but this also appears not to work. I am
> using cabal 1.22 so I don't see why I need cabal-dev but eclipsefb does not
> seem to recognise sandboxes it didn't create itself. I went into the
> project sandbox which I have configured with "Use Cabal Sandboxes" and "Use
> same sandbox for all projects in workspace" but when I force the project to
> build it still fails claiming the dependencies are not met. Indeed, if I do
> a "cabal install dependancies" it installs to my main .cabal directory and
> breaks everything again (project won't build because it can't find
> cabal.1.22....). Am I meant to be using the legacy cabal-dev here? I'm at a
> loss how this works at all with the newest version of eclipsefp.
>
> [1] When I first tried this, I configured eclipsefb with my cabal and
> restarted. This caused eclipsefp to create its own sandbox under
> .metadata/.plugins. It ultimately seemed to fail because it was trying to
> build SourceGraph which crashed, presumably blocking what ever remaining
> steps would have come after it. I made my own sandbox under the .cabal
> directory so that all my workspaces can share the same set of tools, but
> after understanding how this works a bit better I tried to go back to the
> previous configuration... only now eclipsefb doesn't build the sandbox
> anymore and I'm not sure where it tries to install everything because it
> still fails with SourceGraph but now it no longer fills in the path for
> e.g. scion-browser either.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JPMoresmau/eclipsefp/issues/260>.
>



-- 
JP Moresmau
http://jpmoresmau.blogspot.com/

**Comment by jason-johnson** [comment]
One thing I noticed is that Eclipse keeps losing my ghc and cabal locations.  Every time I go to these dialogs, they're empty again.

**Comment by jason-johnson** [comment]
I checked my installation and found that my mac ports installation wasn't in eclipse' path.  I fixed this and created a fresh new workspace.  This caused the build tools to instantly try to install, though there is a different bug I've now reported.  I also clicked "Use Cabal Sandboxes" and "Use same sandbox for all projects in this workspace" but I can't figure out how to get eclipsefb to use it.  It doesn't seem to be creating the sandbox and won't try to bring in the missing dependencies.

**Comment by JPMoresmau** [comment]
It's not running a command, it's using the dynamic-cabal library. As before your issue is that Cabal 1.22 is not found.

**Comment by jason-johnson** [comment]
Yep, I found your post online and I fixed that (installed cabal into my user directory which is in PATH).  Now the error is:

    buildwrapper: Left over temporary directory not removed: /var/folders/q3/mzwxb7mj1cv1w0f7_0j3k8gw0000gn/T/dynamic-cabal.95
Prelude.read: no parse

I've wiped the entire workspace and restarted everything but this error persists.

**Comment by jason-johnson** [comment]
UPDATE:  I've completely deleted eclipse, cleared my cabal caches, did `cabal install cabal happy alex`, installed eclipse, fixed application path, installed eclipsefp, created a fresh new workspace, created a new haskell project.  Still getting  `Prelude.read` error.

This should be fairly easy to reproduce if you know any one else with a mac.  The problem has to be in build wrapper or one of the tools it uses.  I tried making the calls on the command line and I get the same error but I couldn't see anyway to see what was causing it.  The only thing I can think to try would be downloading HEAD from build wrapper and trying that, but I'm concerned that it's actually some other tool build wrapper uses that is broken.

**Comment by jason-johnson** [comment]
I've traced the error into `BuildWrapper/src/Language/Haskell/BuildWrapper/Cabal.hs`, method `cabalConfigure`, expression

    tgs <- DCD.runQuery (DCD.on DCD.localPkgDesc DCD.targets) setup_config

It seems that `tgs` throws `Prelude.read error` when evaluated.  I guess I'll have to trace into Dynamic Cabal now (unless you see a shortcut already).

**Comment by jason-johnson** [comment]
Ok, so I had dynamic-cabal generate the first query file and then stop, loaded that file up in the debugger and I found that a call to read was hiding the real error:

Which is that setup-config is not valid.

    fmap ((( unlines) . drop 1) . lines) $ System.IO.readFile"/Users/jason/EclipseWorkspaces/Frobo/frobJJ/.dist-buildwrapper/dist/setup-config" 
"\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ETXghc\NUL\NUL\NUL\NUL\NUL\NUL\NUL\DC2/opt/local/bin/ghc\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\SOH\SOH\SOH\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL*** Exception: /Users/jason/EclipseWorkspaces/Frobo/frobJJ/.dist-buildwrapper/dist/setup-config: hGetContents: invalid argument (invalid byte sequence)

This is apparently a local related error.  I'm not sure what is creating this setup-config so I'm not sure what I need to be fixing the local on.

**Comment by jason-johnson** [comment]
Success!  I cleaned everything out and dropped down to cabal-1.20 and now everything works.  This can probably be closed but I first want to verify that I can create this situation completely with cabal-1.22 with no involvement of build wrapper or anything else.  Sorry for the spam. :)
