### ISSUE TITLE
alex and happy are not automatically installed which causes tool installs to fail

### ISSUE THREAD

**Issue by jason-johnson** [JPMoresmau/eclipsefp#261]
When I start up a fresh workspace eclipsefb creates its own sandbox and begins trying to load all the tools it requires.  This works correctly but haskell-src always fails complaining that the happy program is not found.  After the tool building phase is finished, none of the tools are in the sandbox/bin folder and none of the Haskell Helper programs are set.

I went into .metadata/.plugins/net.sf.eclipsefp.haskell.ui/sandbox and installed alex and happy myself then restarted eclipse.  On the next start the tools installed correctly and the Haskell Helper Programs tabs were all filled in correctly.

My recommendation would be that when a new sandbox is created that either alex and happy are installed first and then other helper programs or all requirements are passed to cabal at once.

**Comment by JPMoresmau** [comment]
EclipseFP doesn't care about Happy. this is a haskell-src-exts issue. EclipseFP cannot hardcode all the dependencies and quirks libraries it require may or may not use.
