### ISSUE TITLE
cabal-1.22.0.0 missing test configuration run options

### ISSUE THREAD

**Issue by razvan-panda** [JPMoresmau/eclipsefp#264]
After updating from cabal-1.20.0.6 to cabal-1.22.0.0 buildwrapper outputs in Console:

    configuring because setup_config not present
    buildwrapper.exe: Left over temporary directory not removed: C:\Users\Freeman\AppData\Local\Temp\dynamic-cabal.19
    Prelude.read: no parse
    configuring because setup_config not present
    buildwrapper.exe: Left over temporary directory not removed: C:\Users\Freeman\AppData\Local\Temp\dynamic-cabal.20
    Prelude.read: no parse

Because of this right clicking on the project and then on `Run As` will not show the HTF, Cabal, Test-framework options - it only shows the `Run Configurations...` option.

![](http://i.imgur.com/Eb4CFOP.png)

Environment: Windows 8.1 64 bit
GHC: 7.8.3

and

Environment: Arch Linux 64 bit
GHC: 7.8.4

On Windows I got this fixed by downgrading to cabal-1.20.0.6 and choosing it from the `Helper executables` -> `Cabal implementations` setting; but on Arch Linux the test configuration options are still missing from the menu even after downgrading.

On Windows when opening a project buildwrapper outputs:

"[]
[]"

and on Arch Linux it outputs nothing (even in buildwrapper debug mode).

Related issues:
* https://github.com/JPMoresmau/eclipsefp/issues/260
* https://github.com/JPMoresmau/eclipsefp/issues/257

**Comment by JPMoresmau** [comment]
This is a BuildWrapper issue: https://github.com/JPMoresmau/BuildWrapper/issues/52. It won't be fixed quickly because BuildWrapper uses dynamic-cabal that doesn't work with Cabal 1.22, and I have no idea how to make it work. The Cabal guys changed things without asking downsteam projects what the impact would be.

**Comment by razvan-panda** [comment]
Any idea how to make it work on Linux, GHC 7.8.4, cabal-1.20.0.6? I deleted the EclipseFP sandbox, the .ghc and cabal folders and reinstalled ghc and cabal-1.20.0.6 but I'm still getting an error:

    configuring because setup_config not present
    Resolving dependencies...
    Configuring TutorialHTF-0.1...
    buildwrapper: Left over temporary directory not removed: /tmp/dynamic-cabal.4
    <command line>: cannot satisfy -package Cabal-1.20.0.3
        (use -v for more information)
    configuring because setup_config not present
    Resolving dependencies...
    Configuring TutorialHTF-0.1...
    buildwrapper: Left over temporary directory not removed: /tmp/dynamic-cabal.5
    <command line>: cannot satisfy -package Cabal-1.20.0.3
        (use -v for more information)
    configuring because setup_config not present
    Resolving dependencies...
    Configuring TutorialHTF-0.1...
    buildwrapper: Left over temporary directory not removed: /tmp/dynamic-cabal.6
    <command line>: cannot satisfy -package Cabal-1.20.0.3
        (use -v for more information)

Similar problem on Ubuntu.

**Comment by razvan-panda** [comment]
On Linux Mint with GHC 7.8.3 and cabal-install version 1.18.0.5 the test configuration run options are also missing.

The output from buildwrapper after enabling the debug logs is:

	/home/freeman/Software/eclipse/.eclipsefp/sandbox/bin/buildwrapper components --tempfolder=.dist-buildwrapper --cabalpath=/usr/local/haskell/ghc-7.8.3-x86_64/bin/cabal --cabalfile=/home/freeman/Projects/EclipseF
	P-HTF-test-example/TutorialHTF.cabal --cabalflags= --cabaloption=--with-ghc=/usr/local/bin/ghc --logcabal=true
	build-wrapper-json:[[{"Library":true},{"t":"TutorialTest","TestSuite":true}],[]]

Without debug logs enabled, nothing is shown.

Unless I am doing the same configuration mistake on all environments it is highly probable that the testing GUI does not work on Linux Mint, Ubuntu or Arch regardless of GHC / cabal-install version.

**Comment by JPMoresmau** [comment]
I have no idea what you're talking about and what your problem is. The output you show is perfectly normal. The title of this issue is about Cabal 1.22, I don't see the link.

**Comment by razvan-panda** [comment]
@JPMoresmau: The problem is obviously the same: "missing test configuration run options". But since the solution is different, you are right - it needs a new issue, so I will create a new issue.
