### ISSUE TITLE
GUI test runner does not work on Linux systems

### ISSUE THREAD

**Issue by razvan-panda** [JPMoresmau/eclipsefp#267]
This bug was reproduced on:

Arch Linux
GHC 7.8.4 or GHC 7.8.4
cabal-install-1.20.0.6

Linux Mint
GHC 7.8.3
cabal-install version 1.18.0.5

Ubuntu Linux
GHC 7.8.3
cabal-install-1.20.0.6

After buildwrapper does its stuff, right clicking on the project and then on `Run As` will not show the HTF, Cabal, Test-framework options - it only shows the Run Configurations... option:

What is happening:

![](http://i.imgur.com/SkHu1lc.png)

What is expected:

![](https://camo.githubusercontent.com/de5c446c78761d3c8e490baca07ad7a9ee9e23d5/687474703a2f2f692e696d6775722e636f6d2f45623443464f502e706e67)

Trying to run a test using the shortcut <kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>x</kbd>, <kbd>f</kbd> shows an empty `Select Launch Configuration`:

![](http://i.imgur.com/1L35y6R.png)

**Comment by JPMoresmau** [comment]
This only works if the executable has been built. Is that the case? Have you built your project? Look for executables under .dist-buildwrapper/dist in your project directory

**Comment by razvan-panda** [comment]
The test executables were not being built so I followed your advice from https://github.com/JPMoresmau/eclipsefp/issues/96.

The test run configurations appear in the menu after doing:

    cabal configure --builddir=.dist-buildwrapper/dist --enable-tests
    cabal build --builddir=.dist-buildwrapper/dist

    close project
    close eclipsefp
    open eclipsefp
    open project

And then the IDE shown the actual problem it was having:

    buildwrapper: could not execute: htfpp

The solution was fixing the $PATH used by EclipseFP (same problem as described in http://stackoverflow.com/q/27650702/750216), set path in `/etc/environment` to start with the `.cabal/bin` (location of htfpp executable) and restart pc/login session:

PATH="/home/freeman/.cabal/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
