### ISSUE TITLE
Got issues with buildwrapper: "Cabal file does not exist"

### ISSUE THREAD

**Issue by vdudouyt** [JPMoresmau/eclipsefp#268]
Hi!

I'm trying to create a project with EclipseFP 2.6.3.201501121809 on Eclipse 4.4.0 "Luna" and Ubuntu 14.04 and, unfortunately, I'm getting stucked on the following output:

```nohighlight
BuildWrapper output for project hello
----------------------------------------------------
configuring because setup_config not present
Cabal file/home/user/workspace-haskell/hello/hello.cabal does not exist
configuring because setup_config not present
Cabal file/home/user/workspace-haskell/hello/hello.cabal does not exist
```

In addition to that, there is a strange error window that pop-ups at the same time moment. It's text area is empty, and the title states nothing more that there is 'A problem occurred'.

Could you please provide me any suggestions about what may be causing that? Thank you very much for your time!
Valentin

**Comment by JPMoresmau** [comment]
Er, does the cabal file exist? the code that prints that error is fairly straightforward...

**Comment by vdudouyt** [comment]
It doesn't exists indeed. But shouldn't it be automatically initialized when creating new project?

**Comment by JPMoresmau** [comment]
Well, yes it should. Is there any errors in the Eclipse error log? Can you detail the steps you did to create the project?

**Comment by vdudouyt** [comment]
Here is my .log: https://gist.github.com/vdudouyt/1d856b3e5937b46168c5
It contains just a single error message, and it's exactly the one that getting reproduced when this problem happens. (Of course, that's because I've cleared it and restarted Eclipse before testing next time).

I'm creating it in a really-really simple and common (in my opinion) way: just navigate to File -> New -> Haskell Project in Menu, type the project name and press 'Finish'. And then a strange error popup  occurs. The error message in .log (the one that you see on gist) is getting printed exactly after I press 'OK'.

![eclipse_screen](https://cloud.githubusercontent.com/assets/1840936/5942644/a827962c-a73a-11e4-987a-cdb6e14b0664.png)

Do I understand right that I'm getting some kind of API mismatch between Eclipse and EclipseFP? Or some cross-platform issues, maybe?

**Comment by JPMoresmau** [comment]
Regression of 2.6.3 it seems, funny that nobody noticed. You can always create the cabal file by hand or via cabal init, I'll try to release 2.6.4 with the fix quickly.
