### ISSUE TITLE
Dependency libs are not automatically installed locally for a project

### ISSUE THREAD

**Issue by varosi** [JPMoresmau/eclipsefp#277]
When I open my project in EclipseFP, I got in the console:
Configuring png2svg-0.1...
cabal.exe: At least the following dependencies are missing:
JuicyPixels -any, blaze-svg -any

I have not installed those two libraries for the user, because I use sand box and I want those libraries to be installed locally only for the project!

From command-line everything is working fine:
cabal sandbox init
cabal configure
cabal install --only-dependencies

and there are no problems.

I have those options for Haskell Sanboxing into EclipseFP:
Use cabal sandboxes -> Enabled
Use one sandbox for all projects in workspace -> Disabled
Manage project dependencies automatically -> Enabled

EclipseFP 2.6.4
Eclipse Luna Service Release 1a (4.4.1)
cabal 1.20.0.6

buildwrapper executable, version 0.9.1
using version 1.18.1.3 of the Cabal library

Windows 8.1 x64

**Comment by JPMoresmau** [comment]
Well from the command-line you do specify you want to install the dependencies. Do the same in EclipseFP (right click on the project and Cabal install dependencies or use the quick fix on the problem marker).

**Comment by varosi** [comment]
Yes, but when I choose "Cabal install dependencies" it gives me this message:
![eclipse](https://cloud.githubusercontent.com/assets/6051718/6609555/c16ce6c2-c85b-11e4-99b1-3f230268dc57.png)
If I press "Install in sandbox" it open Folder selection dialog. 
Why do I need to select a folder? Isn't there already default folder for that?

EclipseFP is not command-line. It is much more! It should be easy to use, not to put stones on each corner. That is why I proposed that feature to be automatic with build process. I use sandboxing and that it is all about - for dependencies installed separately for my project.

**Comment by JPMoresmau** [comment]
It shows that dialog if you don't have a single sandbox, so you can install project dependencies in another sandbox. If you use one sandbox for your whole workspace, the install dependencies doesn't prompt you for anything.

**Comment by varosi** [comment]
It's good. It would be great if there is a default sandbox location into the project folder. I think most of the people will not use custom sandboxes. And if there is a possibility to change this default from settings it will be just enough.
It will be consistent with the behaviour when you have shared sandbox for the workspace. It has its own default folder. Why not project sandboxes to have their defaults, too.
