### ISSUE TITLE
What controls the location of .eclipsefp on Linux?

### ISSUE THREAD

**Issue by vlatkoB** [JPMoresmau/eclipsefp#283]
Hello,

What controls the location of `.eclipsefp` directory on Linux (Arch and Mint)?

I have `.eclipsefp` in $HOME, and also inside (some) sandboxed projects. Each is rather large, almost 150 000 files and 1 GB of space.
It is than synchronized to .dist-buildwrapper, and it last very, very long time.

I have `Gather information from Hackage` turned off.
I'm using stackage-cli and have common shared sandboxes in $HOME/.stackage, but `Use one sandbox for all projects` is turned off in Preferences because not all projects use the same LTS.

Best regards,
vlatko

**Comment by JPMoresmau** [comment]
You may look at https://github.com/JPMoresmau/eclipsefp/issues/270. Mistakenly, 2.6.4 puts .eclipsefp in user.dir (the current folder) instead of user.home. Get EclipseFP from source if you want the current version.

**Comment by vlatkoB** [comment]
Thanks for the answer.
